version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A tasks beat --loglevel=INFO
    depends_on:
      - redis
      - celery
